### ISSUE TITLE
Swiss flag is a rectangle, not oblong

### ISSUE THREAD

**Issue by adrianegger** [Yummygum/flagpack-core#16]
## Please check all that apply
- [X] visual bug
- [ ] functional bug
- [ ] able to consistently reproduce

## Expected Behavior
Swiss flag should be a rectangle.

## Current Behavior
Swiss flag is oblong.

**Comment by donovanroubos** [comment]
Hi @adrianegger, thanks for submitting this visual bug. I've added the bug to the backlog. We'll keep you posted in this issue.

**Comment by donovanroubos** [comment]
@adrianegger After discussing this with the team we won't be adding exceptions like these in the near future. This will be really intensive to maintain.

You can do this by yourself of course😄! Every flag component contains a property that you can add your own `class`, so you can add your own exceptions/customizations. If you've any further questions, let us know.
