### ISSUE TITLE
Swiss Flag should be Square

### ISSUE THREAD

**Issue by ntzog** [Yummygum/flagpack-core#26]
## Please check all that apply

- [√] visual bug

## Expected Behavior

Swiss Flag should be Square

![Screen Shot 2021-01-25 at 4 44 52 PM](https://user-images.githubusercontent.com/2212334/105770005-ad8f9500-5f2c-11eb-9863-3afcc1e9467e.png)

## Current Behavior

Swiss flag is rectangle

## Possible Solution

Make it square. → https://en.wikipedia.org/wiki/Flag_of_Switzerland

**Comment by noudadrichem** [comment]
See #16
