### ISSUE TITLE
Missing ISO 3166-1 alpha-3 and numeric for United Kingdom 

### ISSUE THREAD

**Issue by ricomadiko** [Yummygum/flagpack-core#33]
In the Flagpack index, **United Kingdom** is currently unable to filter via alpha-3 and numeric as they are missing.

## Expected Behavior
United Kingdom should associate with an alpha-3 and numeric value.

According to these sources:
- https://en.wikipedia.org/wiki/Country_codes:_U%E2%80%93Z
- https://www.iso.org/obp/ui/#iso:code:3166:GB

The value of alpha-3 and numeric for United Kingdom should
- Numeric: **836**
- Alpha-2: **GBR**

## Current Behavior
There are no ISO 3166-1 alpha-3 and numeric for United Kingdom

**Comment by daoneandonly** [comment]
Hi @ricomadiko 👋 Thanks for reporting this issue. We'll make sure the alpha-3 and numeric codes for United Kingdom will be added.

We will keep you posted here once this is resolved.
