### ISSUE TITLE
Allow the svg to be converted to base64 (so it can be imported in the packages)

### ISSUE THREAD

**Issue by yannick1691** [Yummygum/flagpack-core#4]
As part of #Hacktoberfest we thought we reach out to the community and ask for help with a issue we have been trying to resolve for a while now. 

Currently in the vue-flagpack, react-flagpack and angular-flagpack we load the images using the GitHub gist url. This instead should be a local image (for example compiled to a base64 image)

## Detailed Description

In the flagpack packages, the src should be a base64 url instead of the GitHub url. As this is needed for all packages it would most likely be the smartest to do this transform in the core.

## Relevant repos
[react-flagpack](https://github.com/Yummygum/react-flag-pack)
[vue-flagpack](https://github.com/Yummygum/vue-flag-pack)
[angular-flagpack](https://github.com/Yummygum/angular-flag-pack)

## Is your feature request related to a problem? Please describe.

This has the following benefits:
- Icons will stay the same as the version of the core
- The network requests for the flags will not be made to GitHub
- The images are not depended on GitHub

## Describe the solution you'd like
The files to be either imported from the core, or resolving the import to a base64 url.

**Comment by fredericbonnet** [comment]
Hi! I'm willing to work on this issue. I had a quick look at the code and I think it should be doable in reasonable time. Please be aware that this will increase the size of your bundle, though.

**Comment by yannick1691** [comment]
Hey @fredericbonnet this would be fine as we believe this outweights the increase in bundle size.

As making a lot of network request to GitHub also slows down the performance by a lot.

**Comment by noudadrichem** [comment]
Hi @fredericbonnet and @yannick1691,

It should be able to tree shake the flag that is used from out the component per framework. Say I'm using React with the NL flag. I only need the NL flag in my bundle. A bit low prio but should be thought about while developing. Thanks in Advance. I'm also curious about your solution!
