### ISSUE TITLE
Missing Algeria flag

### ISSUE THREAD

**Issue by borisk47** [Yummygum/flagpack-core#40]
country code DZ

**Comment by donovanroubos** [comment]
Hi @borisk47 👋 

Thanks for reporting this issue! 

We did some research and we came with the conclusion that the flag is definitely made by the design team in Figma, but it isn't added to the core and related component packages. We'll make sure the Algerian flag will be published in the upcoming new release.

Just keep an eye out on the new upcoming updates very soon 🙆‍♂️ .

**Comment by daoneandonly** [comment]
We're happy to share that Algeria is included in flagpack-core `v2.0.0`.
Algeria can be used with the following codes:
- `alpha2`: `"DZ"`
- `alpha3`: `"DZA"`
- `numeric`: `"012"`
