### ISSUE TITLE
United Nations Flag

### ISSUE THREAD

**Issue by duncangraham** [Yummygum/flagpack-core#43]
Would love a general catch all flag for international uses

## Detailed Description
Either the UN flag or one of these could work https://en.wikipedia.org/wiki/Flag_of_Earth

**Comment by duncangraham** [comment]
Made this as a stop gap: https://www.figma.com/file/fh5XywZYumgX18bEzJN5Bc/UN-United-Nations?node-id=0%3A1

**Comment by daoneandonly** [comment]
Hi @duncangraham. Thanks for thinking along with Flagpack. Currently we're working toward making Flagpack reflect the ISO 3166 standard. Ironically enough, while this standard is in part set by the United Nations, the flag of the UN itself is not part of this standard. For that reason, we unfortunately have no plans to include the flag of the United Nations into Flagpack.
