### ISSUE TITLE
swiss flag should be square

### ISSUE THREAD

**Issue by udos** [Yummygum/flagpack-core#55]
nice library! thank you!

this might look like a non relevant issue to most of the people (the ones which don't know that the swiss flag is square) but for the ones knowing that the swiss flag is square, seeing it rectangular looks really strange...

## Please check all that apply

- [X] visual bug
- [ ] functional bug
- [ ] able to consistently reproduce

## Expected Behavior
the swiss flag is square (https://en.wikipedia.org/wiki/Flag_of_Switzerland)
![image](https://user-images.githubusercontent.com/141107/128990977-c33a6685-8379-45db-82f9-950da0217fde.png)
note: the rectangular shape is offically allowed only on vessels

## Current Behavior
the flag is rectangular
![image](https://user-images.githubusercontent.com/141107/128992154-1b0fbcd1-c5f2-42af-873a-9271abf58bf9.png)

**Comment by noudadrichem** [comment]
See #16

**Comment by udos** [comment]
sorry about this. did not check closed issues :|
