### ISSUE TITLE
European Union (EU) flag not as SVG, but found in flag index 😆

### ISSUE THREAD

**Issue by eliuddyn** [Yummygum/flagpack-core#60]
## Detailed Description
European Union (EU) flag not as SVG, but found in flag index.

## Describe the solution you'd like
Add the European Union (EU) flag as SVG file.

## Additional context
![Flag Issue](https://user-images.githubusercontent.com/7809471/133942219-0cb5e732-64c8-4c87-8f10-75e8a249f69c.PNG)

**Comment by daoneandonly** [comment]
The flag index is based on our `flagpack-vue` package which unfortunately isn't yet updated to use our new library of flags. This causes a discrepancy between our flag index and the actual use of our package. Sorry for the inconvenience or confusion this may cause, but know that updating this package and therefore the flag-index is planned.

**Comment by eliuddyn** [comment]
> The flag index is based on our `flagpack-vue` package which unfortunately isn't yet updated to use our new library of flags. This causes a discrepancy between our flag index and the actual use of our package. Sorry for the inconvenience or confusion this may cause, but know that updating this package and therefore the flag-index is planned.

Thanks for the response. Very accurate. 🔥🔥

**Comment by darronz** [comment]
@daoneandonly Will you be updating the core package so that it includes the EU flag?

**Comment by activivan** [comment]
> @daoneandonly Will you be updating the core package so that it includes the EU flag?

Any updates on this? The EU flag has many use cases, many services differenciate between EU and US for example

**Comment by bernhardberger** [comment]
We just stumbled upon the same problem.. flagpack.xyz lists it but it isn't here..
