### ISSUE TITLE
Missing mask definition in the Côte d'Ivoire (Ivory Coast) flag

### ISSUE THREAD

**Issue by SimpleCreations** [Yummygum/flagpack-core#72]
https://github.com/Yummygum/flagpack-core/blob/main/lib/flags/s/CIV.svg
This file is missing a mask definition referenced in `mask="url(#CIV_svg__CI_-_Côte_d'Ivoire_(Ivory_Coast)"`.

While browsers seem to ignore this, this breaks `react-native-svg`, which doesn't render the flag at all.

## Please check all that apply

- [ ] visual bug
- [x] functional bug
- [x] able to consistently reproduce

## Expected Behavior

The SVG file is valid.

## Current Behavior

The SVG file is missing a mask definition.

**Comment by daoneandonly** [comment]
Thanks for your thoughts! These masking issues seem to appear in a few flags. I'll close issue here as a duplicate and add the specifics to #62.
