### ISSUE TITLE
Kenya flag clipping issue

### ISSUE THREAD

**Issue by smbkr** [Yummygum/flagpack-core#95]
## Please check all that apply

- [x] visual bug
- [ ] functional bug
- [ ] able to consistently reproduce

## Expected Behavior

It should look correct

<img width="354" alt="Screenshot 2023-08-11 at 17 02 28" src="https://github.com/Yummygum/flagpack-core/assets/933535/f5212fec-2894-4abd-98ea-b8e032c54f30">

## Current Behavior

it doesn't look correct

<img width="58" alt="Screenshot 2023-08-11 at 16 57 46" src="https://github.com/Yummygum/flagpack-core/assets/933535/065084bc-9bcc-480b-a342-d469de43436d">

## Possible Solution

Clipping paths for the circles used on the shield are incorrect/missing, so the circles cover most of the flag

## Your Environment

* Version used: latest commit to main c023e0e602b07e67ca150df70cf8a7cfe3000ddc

**Comment by donovanroubos** [comment]
Hi @smbkr we've also fixed this flag in the `main` repository. Thanks for mentioning!
